"use client";
import {useState} from "react";
const durations=[1,3,5,10,30,60];
const steps=[
 ["IDEA","Your concept"],["AI STORY","Plot, scenes and continuity"],["CHARACTERS","Consistent characters"],["STORYBOARD","Automatic scene breakdown"],["AI VIDEO","Generate cinematic scenes"],["AUDIO","Dialogue, narration, SFX and music"],["MOVIE","Assemble the final timeline"],["EXPORT","Social-ready export"]
];
export default function Home(){
 const[idea,setIdea]=useState(""); const[genre,setGenre]=useState("Cinematic"); const[minutes,setMinutes]=useState(1); const[aspect,setAspect]=useState("16:9");
 const[status,setStatus]=useState("Ready to create your movie."); const[story,setStory]=useState<any>(null); const[active,setActive]=useState(0); const[generated,setGenerated]=useState<Record<number,string>>({});
 async function generateStory(){if(!idea.trim()){setStatus("Write your movie idea first.");return}setStatus("Building your movie plan...");try{const r=await fetch("/api/story",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea,genre,minutes})});const d=await r.json();if(!r.ok)throw new Error(d.error);setStory(d);setActive(1);setStatus(`Movie plan ready: ${d.sceneCount} scenes for ${minutes} minute(s).`)}catch(e:any){setStatus(e.message||"Something went wrong.")}}
 async function generateScene(scene:any){setActive(4);setStatus(`Submitting Scene ${scene.id} to the video engine...`);try{const r=await fetch("/api/video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:scene.prompt,aspect_ratio:aspect})});const d=await r.json();if(d?.ok){setGenerated(x=>({...x,[scene.id]:JSON.stringify(d.data)}));setStatus(`Scene ${scene.id} submitted successfully.`)}else setStatus(d?.message||d?.error?.message||"Video generation needs FAL_KEY.")}catch{setStatus("Video request failed.")}}
 return <main className="wrap"><nav className="nav"><div className="logo">🎬 ViralMovie AI</div><div className="pill">V3 • Interactive Movie Studio</div></nav>
 <section className="hero"><h1>Turn one idea into a movie.</h1><p>Build your project step by step: story, characters, storyboard, AI video, audio, movie timeline and export.</p></section>
 <section className="grid"><div><div className="card"><h2>Create Movie</h2>
 <label className="label">Movie idea</label><textarea className="textarea" value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Example: A young astronaut lands on Mars and discovers an abandoned city..."/>
 <div className="row"><div><label className="label">Genre</label><select className="select" value={genre} onChange={e=>setGenre(e.target.value)}>{["Cinematic","Action","Drama","Sci-Fi","Horror","Comedy","Fantasy","Thriller"].map(x=><option key={x}>{x}</option>)}</select></div><div><label className="label">Aspect ratio</label><select className="select" value={aspect} onChange={e=>setAspect(e.target.value)}>{["16:9","9:16","1:1"].map(x=><option key={x}>{x}</option>)}</select></div></div>
 <label className="label">Movie duration</label><div className="durations">{durations.map(x=><button key={x} className={`duration ${minutes===x?"active":""}`} onClick={()=>setMinutes(x)}>{x} min</button>)}</div>
 <button className="primary" onClick={generateStory}>Generate Movie Plan</button><div className="status">{status}</div></div>
 {story&&<div className="card panel"><h2>{story.title}</h2><p>{story.logline}</p><div className="notice">{story.sceneCount} scenes • {minutes*60} seconds planned • 5 seconds per scene</div><div className="panel"><h2>Storyboard</h2><div className="scene-grid">{story.scenes.map((scene:any)=><div className="scene" key={scene.id}><h3>Scene {scene.id}</h3><p>{scene.prompt}</p><button onClick={()=>generateScene(scene)}>{generated[scene.id]?"Submitted ✓":"Generate Scene"}</button></div>)}</div></div></div>}</div>
 <aside className="card"><h2>Movie Pipeline</h2><div className="steps">{steps.map(([name,desc],i)=><button key={name} className={`step ${active===i?"active":""} ${i<active?"done":""}`} onClick={()=>{setActive(i);if(i===3&&story)window.scrollTo({top:document.body.scrollHeight/2,behavior:"smooth"})}}><div className="step-top"><b>{i+1}. {name}</b><span className="badge">{i<active?"✓":i===active?"ACTIVE":"OPEN"}</span></div><div className="mini">{desc}</div></button>)}</div><div className="panel notice">{active===0&&"Start with your movie idea."}{active===1&&"Your story and scene plan are ready below."}{active===2&&"Character generation is the next production module."}{active===3&&"Storyboard scenes are available below."}{active===4&&"Choose a scene and press Generate Scene."}{active===5&&"Audio module is planned for the next stage."}{active===6&&"Timeline assembly will combine generated scenes."}{active===7&&"Export will become available when the movie timeline is complete."}</div></aside></section>
 <footer className="footer">ViralMovie AI V3 • Interactive pipeline • FAL/Vidu integration uses private FAL_KEY server-side.</footer></main>
}
